### ISSUE TITLE
Adopt Private Click Measurement as a deliverable

### ISSUE THREAD

**Issue by hober** [privacycg/proposals#1]
I propose we adopt [Private Click Measurement](https://wicg.github.io/ad-click-attribution/index.html), currently a @WICG work item, as a deliverable of this Community Group, with @johnwilander continuing as editor.

Repo: https://github.com/wicg/ad-click-attribution

**Comment by hober** [comment]
WebKit is supportive of this work and of doing this work here.

**Comment by TanviHacks** [comment]
Mozilla is supportive of adopting this API.  We do believe there is some more work to be done to consider fraud.

**Comment by othermaciej** [comment]
Trust Tokens have been discussed as a potential way to alleviate the fraud problem.

**Comment by TanviHacks** [comment]
Mozilla has found some issues with Trust Tokens that need to be worked out, but are in favor of moving Private Click Measurement to a Work Item.

https://github.com/mozilla/standards-positions/issues/262#issuecomment-582937201
https://github.com/mozilla/standards-positions/issues/261#issuecomment-582936824

**Comment by hober** [comment]
With multiple implementers in support, we agree to adopt Private Click Measurement as a work item of the Privacy CG, with @wilander as editor.
