### ISSUE TITLE
Adopt Storage Access API as a deliverable

### ISSUE THREAD

**Issue by hober** [privacycg/proposals#2]
I propose we adopt the Storage Access API as a deliverable of the Community Group. It would facilitate discussion to have a separate repository for it, instead of trying to iron out all of the details in one issue thread at whatwg/html#3338.

The end goal would be to land pull requests in the HTML Standard and other applicable specifications.

**Comment by hober** [comment]
WebKit is supportive of this work and of doing this work here.

**Comment by erik-anderson** [comment]
Microsoft is supportive of adopting this as a deliverable. We are doing work in Chromium involving this API.

**Comment by TanviHacks** [comment]
Mozilla is supportive of adopting the Storage Access API.  It was implemented and shipped in Firefox more than a year ago.

**Comment by hober** [comment]
We've adopted this as a deliverable! I've updated the charter in https://github.com/privacycg/privacycg.github.io/commit/872aff4bc21f3211b73d62a07ef45f8c6a8a744f

**Comment by hober** [comment]
With interest from three implementers and the merging privacycg/privacycg.github.io#1, this is done. Drafting and discussion of the Storage Access API should now happen in https://github.com/privacycg/storage-access/
