### ISSUE TITLE
Fragment Directives API

### ISSUE THREAD

**Issue by eligrey** [privacycg/proposals#40]
I am proposing a specification for adoption by the PrivacyCG that aims to codify a way to read and write fragment directives from all supported location interfaces while accounting for the privacy concerns introduced by accessing potentially privacy-sensitive directives (e.g. `text`).

My proposed spec: https://github.com/eligrey/fragment-directives

Related issue in scroll-to-text spec repository: https://github.com/WICG/scroll-to-text-fragment/issues/128

**Comment by eligrey** [comment]
@zcorpan left some feedback here about permission prompts and determining what directives should be considered sensitive: https://github.com/eligrey/fragment-directives/issues/1

**Comment by eligrey** [comment]
If a majority of participating PrivacyCG members agree that additional privacy boundaries are not necessary, I will change the includeSensitive part of the spec to require secure origins instead of an optional permission prompt.

**Comment by eligrey** [comment]
I intentionally chose to re-use `URLSearchParams` in this spec for implementation simplicity, but I can introduce `URLFragmentDirectives` if there is interest for it. If we re-use `URLSearchParams` there will be a slight API ergonomics concern with the leading `?` in string representation. That could be easily special-cased to be ignored.

Aside from the obvious string representation difference, a `URLFragmentDirectives` constructor could also parse out fragment directives from a full hash fragment.

**Comment by eligrey** [comment]
Full disclosure: I work for Transcend, and we currently use `performance.getEntries()` as part of our implementation of accessing [custom fragment directives for our consent manager SDK](https://docs.transcend.io/docs/consent/reference/debugging-and-testing#config-overrides). We use the compat behavior to help ensure that our URL-based configuration options won't interfere with routing on customer sites.

**Comment by martinthomson** [comment]
@eligrey can you explain why you think Privacy CG is the right forum to develop this proposal?  From what I can see, this is a straightforward extension to [the text fragment work](https://github.com/WICG/scroll-to-text-fragment) that is being developed in WICG.  I would suggest that you seek to engage in that forum, probably with the proponents of that work.

@jyasskin you asked for time on our agenda for this.  Can you give me a little more context?  If we are going to set aside time, then we'd need to know who would be leading that work and what you would hope to achieve.  Is it simply a request to discuss adoption as Eli requests?

**Comment by jyasskin** [comment]
Eli asked someone to agenda+ it in https://w3cping.slack.com/archives/CSVA13FJB/p1696271146530939, so I did.

**Comment by erik-anderson** [comment]
This was discussed on our October 12th call: https://github.com/privacycg/meetings/blob/main/2023/telcons/10-12-minutes.md. While it wasn't captured in the minutes, I think something along the lines of Martin's feedback about taking this proposal to the WICG was given.

@eligrey any objections to closing out this issue here? Feel free to add a pointer to the new location.

**Comment by eligrey** [comment]
Yeah, I'm fine with closing this out. I'll post a new link here once I've moved the proposal over to WICG.

**Comment by eligrey** [comment]
This has been re-proposed under WICG: https://github.com/WICG/proposals/issues/154
